name: "Decode Secrets"

on:
  workflow_call:
    outputs:
      keystore:
        description: "The decoded keystore"
        value: ${{ jobs.decode.outputs.keystore }}
      service_account:
        description: "The decoded service account"
        value: ${{ jobs.decode.outputs.service_account }}
      app_credentials:
        description: "The decoded app credentials"
        value: ${{ jobs.decode.outputs.app_credentials }}

jobs:
  decode:
    environment: development
    runs-on: ubuntu-latest
    outputs:
      keystore: ${{ steps.android_keystore.outputs.filePath }}
      service_account: ${{ steps.service_account_json_file.outputs.filePath }}
      app_credentials: ${{ steps.google_app_credentials.outputs.filePath }}
    steps:
      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Decode Google App Credentials
        uses: timheuer/base64-to-file@v1
        id: google_app_credentials
        with:
          fileName: "google_app_credentials.json"
          encodedString: ${{ secrets.GOOGLE_APP_CREDENTIALS }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: keystore
          path: ${{ steps.android_keystore.outputs.filePath }}
