name: Test Gradle Releases
on:
  schedule:
    - cron: 0 0 * * * # daily
  workflow_dispatch:
  
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Touch local properties
      run: touch local.properties
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - run: gradle build --dry-run # just test build configuration
    
  gradle-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Touch local properties
      run: touch local.properties
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - run: gradle build --dry-run # just test build configuration
